name: Build Client
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v3
        with:
          tags: f8122dac91/godot-4.0-ci-exporter:beta16
          push: false
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: f8122dac91/godot-4.0-ci-exporter:beta16
          options: -v ${{ github.workspace }}:/workdir
          run: |
            cd client
            ./build-ci.sh
      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: client-exports
          path: client/exports
